# pubspec.yaml

name: weather_app
description: A new Flutter project for a simple weather application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  geolocator: ^14.0.2
  shared_preferences: ^2.2.3

  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.2

  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.9
  freezed: ^2.4.7

flutter:
  uses-material-design: true
